# Generated by Django 2.2.12 on 2020-05-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
