# Generated by Django 2.2.12 on 2020-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_projects', '0003_auto_20200525_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration (months)'),
        ),
    ]
