# Generated by Django 2.2.12 on 2020-05-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_projects', '0004_auto_20200525_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='project',
        ),
        migrations.CreateModel(
            name='LanguageToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_projects.ProgrammingLanguage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(through='dev_projects.LanguageToProject', to='dev_projects.ProgrammingLanguage'),
        ),
    ]
