# Generated by Django 2.2.12 on 2020-05-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_projects', '0005_auto_20200525_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='location_city',
            field=models.CharField(default='', max_length=200, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_country',
            field=models.CharField(default='', max_length=200, verbose_name='Country'),
        ),
    ]
